[project]
name = "oop-learning-path"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = ["E501", "W505"]
pycodestyle.max-line-length = 88
pycodestyle.max-doc-length = 72